name: Build and Deploy

on:
  push:
    branches: [ master ]
    paths:
      - .github/**
      - archives/**
      - assets/**
      - build.js
      - index.html
  pull_request:
    branches: [ master ]
    paths:
      - .github/**
      - archives/**
      - assets/**
      - build.js
      - index.html

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        cd ${{ github.workspace }}
        rm -r docs
        mkdir docs
        echo "blog.comame.xyz" | cat > docs/CNAME

        echo "Downloading image comameito/puppeteer-nginx"
        docker pull -q comameito/puppeteer-nginx
        echo "Starting build"
        docker run \
        -v ${{ github.workspace }}:/files comameito/puppeteer-nginx sh -c \
        "service nginx start && npm install && node /files/build.js"

        sudo adduser comame --disabled-password --gecos ""  -q
        sudo chown -R comame:comame docs
        sudo chmod -R 777 docs

    - name: Commit
      run: |
        cd ${{ github.workspace }}
        echo "blog.comame.xyz" | cat > docs/CNAME
        git config --local user.name "GitHib Actions"
        git config --local user.email dev@comame.xyz
        git add docs
        git commit -m "Action: deploy" | exit 0

    - name: Push
      run: |
        cd ${{ github.workspace }}
        remote_repo="https://comame:${{ secrets.TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git push ${remote_repo} master
