name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - .github/**
      - '!.github/workflows/build.yml'
      - docs/**
      - .gitignore
      - README.md
  pull_request:
    branches: [ master ]
    paths-ignore:
      - .github/**
      - '!.github/workflows/build.yml'
      - docs/**
      - .gitignore
      - README.md

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: rm -rf docs
    - run: npm ci
    - run: npm run build

    - name: Commit
      run: |
        git config --local user.name "GitHub Actions"
        git config --local user.email dev@comame.xyz
        git add docs
        git commit -m "Action: deploy" | exit 0

    - name: Push
      run: |
        cd ${{ github.workspace }}
        remote_repo="https://comame:${{ secrets.TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git push ${remote_repo} master
