name: Build and Deploy



on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
   
    - name: Build
      run: |
        docker run
        -v ${{ github.workspace }}:/files comameito/puppeteer-nginx sh -c
        "service nginx start && chmod +x /files/build.js && node /files/build.js"
   
    - name: Commit
      run: |
        cd ${{ github.workspace }}
        git config --user.name "GitHib Actions"
        git config --user.email dev@comame.xyz
        git add docs
        git commit -m "Action: deploy" | exit 0

    - name: Push
      run: |
        cd ${{ github.workspace }}
        remote_repo "https://comame:${{ secrets.TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        git push remote_repo master
