name: Docker

on:
  push:
    branches: [ master ]
    paths:
      - build/comameito_blog-builder/**
      - .github/workflows/docker.yml
  pull_request:
    branches: [ master ]
    paths:
      - build/comameito_blog-builder/**
      - .github/workflows/docker.yml

jobs:
  build:
    name: Docker
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker
      run: |
        cd ${{ github.workspace }}/build/comameito_blog-builder
        docker build --tag comameito/blog-builder .
        docker login -u comameito -p ${{ secrets.DOCKER_PASSWORD }}
        docker push comameito/blog-builder
